version: "3.8"

services:
  postgres:
    image: postgres:latest
    container_name: my_postgres
    environment:
      POSTGRES_USER: myuser # Username
      POSTGRES_PASSWORD: mypassword # Password
      POSTGRES_DB: mydb # Database name
    ports:
      - "5432:5432" # Host:Container port mapping
    volumes:
      - pg_data:/var/lib/postgresql/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "myuser"]
      interval: 10s
      retries: 5
      start_period: 10s
      timeout: 5s

volumes:
  pg_data:
